spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///testdb?useSSL=true
    username: root
    password: 123
mapper:
  identity: MYSQL
  not-empty: true
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.MySqlMapper
#������־��ӡSQL���
logging:
  level:
    com.example.bootssm2.mapper:  debug
